cc_library(
    name = "timey",
    srcs = ["timey.cc"],
    hdrs = ["timey.h"],
    visibility = ["//mainy:__pkg__","//testy:__pkg__"],
)

cc_library(
    name = "triangley",
    srcs = ["triangley.cc"],
    hdrs = ["triangley.h"],
    deps = [
        ":shapey"
    ],
    visibility = ["//mainy:__pkg__","//testy:__pkg__"],
)

cc_library(
    name = "rectangley",
    srcs = ["rectangley.cc"],
    hdrs = ["rectangley.h"],
    deps = [
        ":shapey"
    ],
    visibility = ["//mainy:__pkg__","//testy:__pkg__"],
)

cc_library(
    name = "shapey",
    srcs = ["shapey.cc"],
    hdrs = ["shapey.h"],
    visibility = ["//mainy:__pkg__","//testy:__pkg__"],
)